Repository ti-community-infra/ti-challenge-bot, pull requests merged in 2020-11, with the labels that each got.

#199 ci: fix broken preview
  .github/workflows/preview.yml
Labels: size/XS, status/can-merge

#200 fix: use escape double quotation marks for windows
  package.json
Labels: size/XS, status/LGT1, status/can-merge

#202 test: add test cases for IssueUtil
  .gitignore
  test/services/utils/IssueUtil.test.ts
Labels: size/L, status/LGT1, status/can-merge

#207 fix: use failure status
  src/events/pull/index.ts
Labels: size/XS, status/can-merge
