Repository ti-community-infra/ti-challenge-bot, pull requests merged in 2020-10, with the labels that each got.

#155 fix: use pending status
  src/events/pull/index.ts
Labels: status/can-merge

#156 fix: remove url
  package.json
  release.config.js
  src/index.ts
Labels: status/can-merge

#158 revert: "fix: remove url (#156)"
  src/index.ts
Labels: status/can-merge

#172 feat: add branches config
  src/commands/lgtm/.keep
  src/commands/reward/index.ts
  src/config/Config.ts
  src/events/custom/index.ts
  src/events/pull/index.ts
  src/services/challenge-pull/index.ts
  src/services/utils/PullUtil.ts
  src/services/utils/ReplyUtil.ts
  test/services/utils/PullUtil.test.ts
  test/services/utils/ReplyUtil.test.ts
Labels: size/L, status/can-merge

#174 fix: add rank order
  src/repositoies/score/index.ts
  src/services/challenge-program/index.ts
  src/services/challenge-pull/index.ts
Labels: size/M, status/can-merge

#177 fix: support url regex
  src/services/challenge-program/index.ts
  src/services/messages/ChallengePullMessage.ts
  src/services/utils/PullUtil.ts
  test/services/utils/PullUtil.test.ts
Labels: size/S, status/can-merge
