Repository ti-community-infra/ti-challenge-bot, pull requests merged in 2020-12, with the labels that each got.

#214 chore: fmt app.yml
  app.yml
  src/services/challenge-program/index.ts
  src/services/challenge-team/index.ts
Labels: size/S, status/LGT1, status/can-merge

#205 fix: enhanced command limit
  .gitignore
  src/commands/give-up/index.ts
  src/commands/pick-up/index.ts
  src/commands/reward/index.ts
  src/index.ts
  src/services/challenge-issue/index.ts
  src/services/challenge-pull/index.ts
  src/services/messages/ChallengeIssueMessage.ts
  src/services/messages/ChallengePullMessage.ts
  test/fixtures/pulls.giveup.comment.json
  test/fixtures/pulls.pickup.comment.json
  test/index.test.ts
Labels: size/XL, status/LGT1, status/can-merge

#223 fix: remove reward CI status
  src/events/pull/index.ts
  src/services/challenge-pull/index.ts
Labels: size/M, status/LGT1, status/can-merge
